apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-todo
spec:
  type: {{ .Values.service.type }}

  selector:
    app: todo

  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      nodePort: {{ .Values.service.nodePort }}