jobs:
  test:
    ...

  docker:
    ...

  push-ecr:
    ...

  oidc-debug:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Debug OIDC claims
        uses: github/actions-oidc-debugger@main